### PR TITLE
WL-3258 Instructions on search.

### PR DESCRIPTION
**Pull request by buckett**
Add some examples and instructions to search.

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
Do we have a list on WebLearn somewhere of which browsers we support?  All I can find is this on the Guidance site:


    Best performance can be obtained from

        Internet Explorer 7 and upwards, Internet Explorer 6 is NOT recommended.
        Firefox
        Opera
        Chrome

**Comment by buckett** [comment]
Not that I know of. I don't think this matters if the small percentage of people on older browsers don't see the examples.

**Comment by nicholaswilson100** [comment]
If I remember, placeholder doesn't work with IE9

**Comment by nicholaswilson100** [comment]
yeah

**Comment by nicholaswilson100** [comment]
We shouldn't saying this on the Guidance site though if we're not coding towards it

**Pull request merged**
