### PR TITLE
WL-4030 Performance improvements when exporting courses.

### PR DESCRIPTION
**Pull request by buckett**
Performance improvement in exporting courses.

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
Which bit's the performance improvement? Is it mainly the lazy loading?

**Comment by nicholaswilson100** [comment]
Nice tests

**Comment by nicholaswilson100** [comment]
We don't have many load tests do we... Have you looked at PerformanceTests.java? :)

**Comment by buckett** [comment]
On 30 November 2015 at 11:47, Nick Wilson <notifications@github.com> wrote:

> Which bit's the performance improvement? Is it mainly the lazy loading?
>

It's much better SQL which doesn't perform additional queries for each item
being exported, it loads them all to start with.

It also makes the loading of additional personal details lazy, which means
we don't go back to LDAP as much.

-- 
  Matthew Buckett, VLE Developer, IT Services, University of Oxford

**Comment by buckett** [comment]
PerformanceTests.java?

**Pull request merged**
